name: Mainnet

on:
  push:
    branches: [ main ]


jobs:
  build-deploy:
    concurrency: mainnet
    environment:
      name: mainnet
      url: https://explorer.xrplf.org/rEGGDggxupqxJ3ZbDTLUzKtpHxHyhtUtiU
    env:
      XRPL_NODE_JSON_RPC_URL: https://xrplcluster.com
      XRPL_NODE_ENVIRONMENT: Mainnet
      STACK_NAME: xrpl-price-oracle-sam-livenet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: sam build
      - name: Deploy
        run: >-
          sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --stack-name $STACK_NAME
          --capabilities CAPABILITY_IAM
          --parameter-overrides="
            ParameterKey=GitCommit,ParameterValue=\"$GITHUB_SHA\"
            ParameterKey=XRPLNodeJsonRpcUrl,ParamaterValue=\"$XRPL_NODE_JSON_RPC_URL\"
            ParameterKey=XRPLNodeEnvironment,ParameterValue=\"$XRPL_NODE_ENVIRONMENT\"
          "
          --s3-bucket "${{ secrets.SAM_DEPLOY_BUCKET }}"
          --region us-east-1
