name: Testnet

on:
  # When you need to test, branch configurations for the mainnet workflow,
  # uncomment this
  # push:
  #   branches: [ dev-gh-action ]
  pull_request:
    branches: [ main ]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build-deploy:
    environment: 
      name: testnet
      url: https://explorer-testnet.xrplf.org/rayZw5nJmueB5ps2bfL85aJgiKub7FsVYN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: sam build
      - name: Deploy
        env:
          XRPL_NODE_JSON_RPC_URL: https://s.altnet.rippletest.net:51234
          XRPL_NODE_ENVIRONMENT: Testnet
          STACK_NAME: xrpl-price-oracle-sam-test
          GIT_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: >-
          sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --stack-name $STACK_NAME
          --capabilities CAPABILITY_IAM
          --parameter-overrides="
            ParameterKey=GitCommit,ParameterValue=\"$GIT_COMMIT\"
            ParameterKey=XRPLNodeJsonRpcUrl,ParamaterValue=\"$XRPL_NODE_JSON_RPC_URL\"
            ParameterKey=XRPLNodeEnvironment,ParameterValue=\"$XRPL_NODE_ENVIRONMENT\"
          "
          --s3-bucket "${{ secrets.SAM_DEPLOY_BUCKET }}"
          --region us-east-1
